'use client';

import { useEffect, useRef, useState } from 'react';
import { useRouter } from 'next/navigation';

type Kind='coin'|'boost'|'spring'|'slow'|'kill';
type Obstacle={z:number;lane:-1|0|1;kind:Kind;hit:boolean};
type PlayerState={player:number;x:number;z:number;score:number;finished:boolean};
const LENGTH=5000;
const LANES=[-1,0,1] as const;
const WS_URL=process.env.NEXT_PUBLIC_JUSU_RUSH_WS_URL || '';

function makeTrack():Obstacle[]{
 const pattern:Kind[]=['coin','boost','coin','slow','coin','spring','coin','kill','coin','boost','coin','slow','coin','spring','kill','coin','boost','coin','slow','coin'];
 return pattern.map((kind,i)=>({z:420+i*230+(i%3)*35,lane:LANES[(i*2+1)%3],kind,hit:false}));
}

function Ball({x,y,r,color}:{x:number;y:number;r:number;color:string}){
 return <div style={{position:'absolute',left:x-r,top:y-r,width:r*2,height:r*2,borderRadius:'50%',background:`radial-gradient(circle at 35% 30%,#fff 0 7%,${color} 22%,#07101d 78%)`,boxShadow:`0 0 22px ${color}`}}/>;
}

function ModePicker(){
 const router=useRouter();
 return <main className="min-h-screen bg-[#02060d] text-white"><div className="mx-auto flex min-h-screen max-w-5xl items-center justify-center p-5"><section className="w-full rounded-[32px] border border-white/10 bg-[#09111e] p-6 shadow-2xl sm:p-10"><div className="text-center"><p className="text-xs font-black tracking-[.5em] text-cyan-400">JUSU</p><h1 className="mt-2 text-5xl font-black">RUSH</h1><p className="mx-auto mt-3 max-w-xl text-sm leading-6 text-slate-400">Choose your race. The game name is always JUSU RUSH.</p></div><div className="mx-auto mt-8 grid max-w-3xl gap-4 md:grid-cols-2"><button onClick={()=>router.push('/jusu-rush?mode=ai')} className="rounded-3xl border border-cyan-400/25 bg-cyan-400/[.08] p-6 text-left hover:border-cyan-300"><p className="text-xs font-black tracking-[.18em] text-cyan-400">SINGLE PLAYER</p><h2 className="mt-2 text-2xl font-black">PLAY WITH JUSU</h2><p className="mt-2 text-sm leading-6 text-slate-400">Race against JUSU AI. JUSU is your opponent.</p><span className="mt-5 inline-block rounded-xl bg-cyan-400 px-5 py-3 text-sm font-black text-slate-950">RACE JUSU →</span></button><button onClick={()=>router.push('/jusu-rush?mode=2p')} className="rounded-3xl border border-emerald-400/20 bg-emerald-400/[.06] p-6 text-left hover:border-emerald-300"><p className="text-xs font-black tracking-[.18em] text-emerald-400">MULTIPLAYER</p><h2 className="mt-2 text-2xl font-black">2 PLAYERS</h2><p className="mt-2 text-sm leading-6 text-slate-400">Create a race room or join a friend on another phone. No Firebase.</p><span className="mt-5 inline-block rounded-xl bg-emerald-400 px-5 py-3 text-sm font-black text-slate-950">2-PHONE RACE →</span></button></div><button onClick={()=>router.push('/')} className="mx-auto mt-7 block text-sm font-bold text-slate-500">← Back to Savings</button></section></div></main>;
}

function RaceCanvas({multiplayer=false,playerId=1,remote,onState,remoteFinished}:{multiplayer?:boolean;playerId?:number;remote:PlayerState|null;onState?:(s:PlayerState)=>void;remoteFinished?:boolean}){
 const canvas=useRef<HTMLCanvasElement>(null);
 const [score,setScore]=useState(0),[playing,setPlaying]=useState(false),[paused,setPaused]=useState(false),[dead,setDead]=useState(false),[finished,setFinished]=useState(false),[countdown,setCountdown]=useState<number|null>(null),[status,setStatus]=useState('READY TO RUSH');
 const me=useRef({z:0,lane:playerId===1?-1:1,target:playerId===1?-1:1,speed:0,boost:0,slow:0,spring:0});
 const ai=useRef({z:0,lane:1,target:1,speed:0,boost:0,slow:0,spring:0});
 const track=useRef(makeTrack()); const started=useRef(false); const pausedRef=useRef(false); const scoreRef=useRef(0); const lastSent=useRef(0);
 useEffect(()=>{pausedRef.current=paused},[paused]);
 useEffect(()=>{scoreRef.current=score},[score]);
 const playAgain=()=>{me.current={z:0,lane:playerId===1?-1:1,target:playerId===1?-1:1,speed:0,boost:0,slow:0,spring:0};ai.current={z:0,lane:1,target:1,speed:0,boost:0,slow:0,spring:0};track.current=makeTrack();setScore(0);scoreRef.current=0;setDead(false);setFinished(false);setPaused(false);started.current=false;setCountdown(3);let n=3;const t=window.setInterval(()=>{n--;if(n<=0){window.clearInterval(t);setCountdown(null);started.current=true;setPlaying(true);setStatus('RUSH!')}else setCountdown(n)},650)};
 const togglePause=()=>{if(!started.current||dead||finished||countdown!==null)return;setPaused(v=>!v);setPlaying(v=>!v)};
 useEffect(()=>{
  const c=canvas.current;if(!c)return;const ctx=c.getContext('2d');if(!ctx)return;let raf=0,last=performance.now(),w=0,h=0,touchX=0;const keys=new Set<string>();
  const resize=()=>{const r=c.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);w=r.width;h=r.height;c.width=w*d;c.height=h*d;ctx.setTransform(d,0,0,d,0,0)};
  const kd=(e:KeyboardEvent)=>{keys.add(e.key.toLowerCase());if(['arrowleft','arrowright','a','d',' '].includes(e.key.toLowerCase()))e.preventDefault()};const ku=(e:KeyboardEvent)=>keys.delete(e.key.toLowerCase());
  const ts=(e:TouchEvent)=>{touchX=e.touches[0]?.clientX||0};const tm=(e:TouchEvent)=>{if(!started.current||pausedRef.current)return;const x=e.touches[0]?.clientX||touchX,dx=x-touchX;if(Math.abs(dx)>18){me.current.target=Math.max(-1,Math.min(1,me.current.target+(dx>0?1:-1)));touchX=x}e.preventDefault()};
  const rr=(x:number,y:number,ww:number,hh:number,r:number)=>{ctx.beginPath();ctx.roundRect(x,y,ww,hh,r);ctx.fill()};
  const ball=(x:number,y:number,r:number,color:string)=>{const g=ctx.createRadialGradient(x-r*.35,y-r*.45,2,x,y,r);g.addColorStop(0,'#fff');g.addColorStop(.18,color);g.addColorStop(1,'#06111f');ctx.fillStyle=g;ctx.shadowBlur=18;ctx.shadowColor=color;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0};
  const item=(o:Obstacle,x:number,y:number,sc:number)=>{ctx.save();ctx.translate(x,y);ctx.scale(sc,sc);ctx.textAlign='center';ctx.font='900 9px system-ui';if(o.kind==='coin'){ctx.fillStyle='#facc15';ctx.beginPath();ctx.arc(0,0,11,0,Math.PI*2);ctx.fill();ctx.fillStyle='#713f12';ctx.fillText('$',0,4)}if(o.kind==='boost'){ctx.fillStyle='#22d3ee';rr(-28,-7,56,14,5);ctx.fillStyle='#032b35';ctx.fillText('BOOST',0,4)}if(o.kind==='spring'){ctx.strokeStyle='#c084fc';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(-14,8);for(let i=0;i<5;i++)ctx.lineTo(-14+i*7,i%2?-8:8);ctx.stroke();ctx.fillStyle='#a855f7';ctx.fillRect(-18,8,36,5)}if(o.kind==='slow'){ctx.fillStyle='#2563eb';rr(-28,-7,56,14,5);ctx.fillStyle='#fff';ctx.fillText('SLOW',0,4)}if(o.kind==='kill'){ctx.fillStyle='#ef4444';ctx.beginPath();ctx.moveTo(0,-16);ctx.lineTo(15,12);ctx.lineTo(-15,12);ctx.closePath();ctx.fill();ctx.fillStyle='#fff';ctx.fillText('!',0,7)}ctx.restore()};
  const loop=(now:number)=>{const dt=Math.min(.033,(now-last)/1000);last=now;const m=me.current;
   if(started.current&&!pausedRef.current&&!dead&&!finished){const dir=(keys.has('arrowleft')||keys.has('a')?-1:0)+(keys.has('arrowright')||keys.has('d')?1:0);if(dir)m.target=Math.max(-1,Math.min(1,m.target+dir*dt*3.5));const boost=keys.has(' ')||m.boost>0;m.speed+=((m.slow>0?4.5:boost?13:8.5)-m.speed)*Math.min(1,dt*5);if(m.boost>0)m.boost=Math.max(0,m.boost-dt);if(m.slow>0)m.slow=Math.max(0,m.slow-dt);if(m.spring>0){m.spring=Math.max(0,m.spring-dt);m.speed+=12*dt}m.lane+=(m.target-m.lane)*Math.min(1,dt*10);m.z=Math.min(LENGTH,m.z+m.speed*dt*60);
    if(!multiplayer){const a=ai.current;const ahead=track.current.filter(o=>!o.hit&&o.z>a.z&&o.z-a.z<420).sort((x,y)=>x.z-y.z)[0];a.target=a.lane;if(ahead&&Math.abs(ahead.lane-a.lane)<.5)a.target=LANES[(LANES.indexOf(a.lane as -1|0|1)+1)%3];if(Math.random()<dt*.45)a.target=LANES[Math.floor(Math.random()*3)];a.lane+=(a.target-a.lane)*Math.min(1,dt*2.8);a.speed+=((a.slow>0?4.2:a.boost>0?12:8.15)-a.speed)*Math.min(1,dt*4);if(a.boost>0)a.boost=Math.max(0,a.boost-dt);if(a.slow>0)a.slow=Math.max(0,a.slow-dt);if(a.spring>0){a.spring=Math.max(0,a.spring-dt);a.speed+=11*dt}a.z=Math.min(LENGTH,a.z+a.speed*dt*60)}
    for(const o of track.current){if(o.hit)continue;const dz=o.z-m.z;if(dz>=-10&&dz<=28&&Math.abs(o.lane-m.lane)<=.42){o.hit=true;if(o.kind==='coin')setScore(v=>v+25);if(o.kind==='boost'){m.boost=2.2;setScore(v=>v+10)}if(o.kind==='spring'){m.spring=1;m.speed+=8;setScore(v=>v+10)}if(o.kind==='slow'){m.slow=2;m.speed*=.5}if(o.kind==='kill'){m.speed=0;started.current=false;setPlaying(false);setDead(true);setStatus('CRASHED')}}}
    if(multiplayer&&onState&&now-lastSent.current>70){lastSent.current=now;onState({player:playerId,x:m.lane,z:m.z,score:scoreRef.current,finished:m.z>=LENGTH})}
    if(m.z>=LENGTH){started.current=false;setPlaying(false);setFinished(true);setStatus('FINISH')}if(multiplayer&&remoteFinished&&m.z<LENGTH){started.current=false;setPlaying(false);setDead(true);setStatus('OPPONENT WINS')}
    if(!multiplayer&&ai.current.z>=LENGTH){started.current=false;setPlaying(false);setDead(true);setStatus('JUSU WINS')}
   }
   ctx.clearRect(0,0,w,h);const sky=ctx.createLinearGradient(0,0,0,h);sky.addColorStop(0,'#061a32');sky.addColorStop(.55,'#0b3652');sky.addColorStop(1,'#03070d');ctx.fillStyle=sky;ctx.fillRect(0,0,w,h);const horizon=h*.28,top=w*.13,bottom=w*1.06;ctx.fillStyle='#182536';ctx.beginPath();ctx.moveTo(w/2-top/2,horizon);ctx.lineTo(w/2+top/2,horizon);ctx.lineTo(w/2+bottom/2,h);ctx.lineTo(w/2-bottom/2,h);ctx.closePath();ctx.fill();for(let lane=-1;lane<=1;lane++){ctx.strokeStyle='rgba(255,255,255,.2)';ctx.setLineDash([18,20]);ctx.beginPath();ctx.moveTo(w/2+lane*top/6,horizon);ctx.lineTo(w/2+lane*bottom/6,h);ctx.stroke();ctx.setLineDash([])}
   for(const o of track.current){const dz=o.z-m.z;if(o.hit||dz<8||dz>1100)continue;const p=1-dz/1100,y=horizon+p*p*(h-horizon),rw=top+p*(bottom-top),x=w/2+o.lane*rw/6;item(o,x,y,.35+p*1.5)}
   const px=w/2+m.lane*bottom/6;ball(px,h*.79,Math.max(23,w*.042),playerId===1?'#38bdf8':'#a78bfa');const other=multiplayer?remote:ai.current;const oz=other?.z??0,ol=other?.x??(ai.current.lane);const dz=oz-m.z;if(dz>-900&&dz<500){const p=Math.max(0,Math.min(1,1-dz/1100)),y=horizon+p*p*(h-horizon),rw=top+p*(bottom-top),ax=w/2+ol*rw/6;ball(ax,y,Math.max(13,w*.025),playerId===1?'#f97316':'#38bdf8')}
   ctx.fillStyle='rgba(0,0,0,.72)';rr(14,14,Math.min(500,w-28),94,14);ctx.fillStyle='#fff';ctx.font='900 16px system-ui';ctx.fillText(`RUSH  ${Math.floor(m.z)} / ${LENGTH}m`,28,39);ctx.fillStyle=playerId===1?'#38bdf8':'#a78bfa';ctx.fillText(`YOU  ${m.speed.toFixed(1)}x`,28,65);ctx.fillStyle='#f97316';ctx.fillText(`${multiplayer?'PLAYER '+(playerId===1?2:1):'JUSU'}  ${((other?.z??0)/60).toFixed(0)}m`,145,65);ctx.fillStyle='#facc15';ctx.fillText(`COINS ${scoreRef.current}`,360,65);ctx.fillStyle='rgba(255,255,255,.12)';rr(28,77,Math.min(440,w-56),5,3);ctx.fillStyle='#22d3ee';rr(28,77,Math.min(440,w-56)*m.z/LENGTH,5,3);
   if(countdown!==null){ctx.fillStyle='rgba(0,0,0,.45)';ctx.fillRect(0,0,w,h);ctx.fillStyle='#fff';ctx.textAlign='center';ctx.font='900 92px system-ui';ctx.fillText(countdown>0?String(countdown):'RUSH!',w/2,h*.52);ctx.textAlign='left'}if(paused){ctx.fillStyle='rgba(0,0,0,.58)';ctx.fillRect(0,0,w,h);ctx.fillStyle='#fff';ctx.textAlign='center';ctx.font='900 52px system-ui';ctx.fillText('PAUSED',w/2,h*.48);ctx.textAlign='left'}if(dead||finished){ctx.fillStyle='rgba(0,0,0,.7)';ctx.fillRect(0,0,w,h);ctx.textAlign='center';ctx.fillStyle=finished?'#facc15':'#ef4444';ctx.font='900 48px system-ui';ctx.fillText(finished?'🏁 YOU WIN':status,w/2,h*.46);ctx.fillStyle='#fff';ctx.font='700 18px system-ui';ctx.fillText('Press PLAY AGAIN for a fresh race',w/2,h*.54);ctx.textAlign='left'}raf=requestAnimationFrame(loop)};
  resize();window.addEventListener('resize',resize);window.addEventListener('keydown',kd);window.addEventListener('keyup',ku);c.addEventListener('touchstart',ts,{passive:false});c.addEventListener('touchmove',tm,{passive:false});raf=requestAnimationFrame(loop);return()=>{cancelAnimationFrame(raf);window.removeEventListener('resize',resize);window.removeEventListener('keydown',kd);window.removeEventListener('keyup',ku);c.removeEventListener('touchstart',ts);c.removeEventListener('touchmove',tm)}} ,[multiplayer,playerId,remote?.z,remote?.x,remoteFinished,dead,finished,countdown,paused]);
 return <div className="relative h-[68vh] min-h-[520px] w-full overflow-hidden rounded-2xl border border-white/10 bg-black"><canvas ref={canvas} className="block h-full w-full touch-none"/></div>;
}

function TwoPlayer(){
 const router=useRouter();const ws=useRef<WebSocket|null>(null);const [room,setRoom]=useState(''),[joined,setJoined]=useState(false),[player,setPlayer]=useState<1|2>(1),[players,setPlayers]=useState(0),[remote,setRemote]=useState<PlayerState|null>(null),[message,setMessage]=useState('Connect two phones to the same room.'),[started,setStarted]=useState(false),[serverError,setServerError]=useState('');
 const connect=(action:'create'|'join')=>{setServerError('');if(!WS_URL){setServerError('Set NEXT_PUBLIC_JUSU_RUSH_WS_URL to the deployed JUSU RUSH WebSocket server.');return}const socket=new WebSocket(WS_URL);ws.current=socket;socket.onopen=()=>{if(action==='create')socket.send(JSON.stringify({type:'create'}));else socket.send(JSON.stringify({type:'join',room:room.trim().toUpperCase(),player:2}))};socket.onmessage=e=>{const m=JSON.parse(e.data);if(m.type==='room_created'){setRoom(m.room);socket.send(JSON.stringify({type:'join',room:m.room,player:1}))}if(m.type==='joined'){setRoom(m.room);setPlayer(m.player);setJoined(true);setPlayers(m.players);setMessage(m.players===2?'Both racers connected. Press START RACE.':'Room ready. Share the code with your friend.')}if(m.type==='state'){const list=m.players as PlayerState[];setPlayers(list.length);const other=list.find((p:PlayerState)=>p.player!==player);if(other)setRemote(other)}if(m.type==='player_left'){setPlayers(1);setStarted(false);setMessage('Your opponent left the room.')}if(m.type==='error')setServerError(m.message)};socket.onerror=()=>setServerError('Could not connect to the multiplayer server.');socket.onclose=()=>{if(joined)setMessage('Connection closed.')}};
 useEffect(()=>()=>ws.current?.close(),[joined]);
 const sendState=(s:PlayerState)=>{if(ws.current?.readyState===WebSocket.OPEN)ws.current.send(JSON.stringify({type:'state',...s}))};
 if(!started)return <main className="min-h-screen bg-[#02060d] text-white"><div className="mx-auto flex min-h-screen max-w-2xl items-center justify-center p-5"><section className="w-full rounded-[32px] border border-white/10 bg-[#09111e] p-7"><button onClick={()=>router.push('/jusu-rush')} className="text-sm font-bold text-slate-500">← JUSU RUSH modes</button><p className="mt-7 text-xs font-black tracking-[.4em] text-emerald-400">JUSU RUSH</p><h1 className="mt-2 text-4xl font-black">2 PLAYERS</h1><p className="mt-3 text-sm leading-6 text-slate-400">Real two-phone race. One player creates a room, the other joins with the code.</p><div className="mt-7 grid gap-3 sm:grid-cols-2"><button onClick={()=>connect('create')} className="rounded-2xl bg-emerald-400 p-4 font-black text-slate-950">CREATE RACE ROOM</button><div className="rounded-2xl border border-white/10 p-4"><input value={room} onChange={e=>setRoom(e.target.value.toUpperCase().slice(0,8))} placeholder="ROOM CODE" className="w-full rounded-xl bg-black/30 px-4 py-3 text-center font-black tracking-[.25em] outline-none"/><button onClick={()=>connect('join')} disabled={room.length<4} className="mt-3 w-full rounded-xl bg-white/10 py-3 font-black disabled:opacity-30">JOIN ROOM</button></div></div>{room&&<div className="mt-5 rounded-2xl bg-black/30 p-5 text-center"><p className="text-xs text-slate-500">ROOM CODE</p><p className="mt-1 text-4xl font-black tracking-[.25em] text-emerald-400">{room}</p><p className="mt-2 text-xs text-slate-500">Share this code with the other phone.</p></div>}{joined&&<div className="mt-4 rounded-2xl border border-emerald-400/20 bg-emerald-400/[.06] p-4 text-center"><p className="font-black">PLAYER {player} · {players}/2 CONNECTED</p><p className="mt-1 text-xs text-slate-400">{message}</p><button onClick={()=>{if(players===2)setStarted(true)}} disabled={players!==2} className="mt-4 rounded-xl bg-emerald-400 px-6 py-3 font-black text-slate-950 disabled:opacity-30">START RACE</button></div>}{serverError&&<p className="mt-4 rounded-xl bg-red-500/10 p-3 text-center text-xs font-bold text-red-400">{serverError}</p>}</section></div></main>;
 return <main className="min-h-screen bg-[#02060d] p-3 text-white sm:p-5"><div className="mx-auto max-w-[1500px]"><header className="mb-3 flex items-center justify-between rounded-2xl border border-white/10 bg-white/[.04] px-4 py-3"><b>JUSU RUSH · 2 PLAYERS</b><span className="rounded-lg bg-emerald-400/10 px-3 py-1 text-xs font-black text-emerald-400">ROOM {room}</span><b>PLAYER {player}</b></header><RaceCanvas multiplayer playerId={player} remote={remote} remoteFinished={!!remote?.finished} onState={sendState}/><div className="mt-3 flex justify-center gap-3"><button onClick={()=>location.reload()} className="rounded-xl bg-white/10 px-5 py-3 text-xs font-black">LEAVE RACE</button></div></div></main>;
}

function AI(){
 const [remote,setRemote]=useState<PlayerState|null>(null);return <main className="min-h-screen bg-[#02060d] p-3 text-white sm:p-5"><div className="mx-auto max-w-[1500px]"><header className="mb-3 flex items-center justify-between rounded-2xl border border-white/10 bg-white/[.04] px-4 py-3"><b className="text-cyan-400">JUSU RUSH</b><span className="text-xs font-black text-red-400">YOU vs JUSU AI</span><span className="text-xs text-slate-500">Touch to steer</span></header><RaceCanvas remote={remote}/></div></main>;
}

export default function JusuRushPage(){const [mode,setMode]=useState<'ai'|'2p'|null>(null);useEffect(()=>{const q=new URLSearchParams(window.location.search).get('mode');setMode(q==='ai'||q==='2p'?q:null)},[]);if(!mode)return <ModePicker/>;if(mode==='2p')return <TwoPlayer/>;return <AI/>;}
