'use client';

import {useEffect,useRef,useState} from 'react';
import {useRouter} from 'next/navigation';

type Kind='coin'|'boost'|'spring'|'slow'|'kill';
type Ob={z:number;lane:-1|0|1;kind:Kind;hit:boolean};
const L=[-1,0,1] as const;
const kinds:Kind[]=['coin','coin','boost','coin','slow','coin','spring','coin','kill','coin','boost','coin','slow','coin','spring'];
const makeTrack=(from:number)=>kinds.map((kind,i)=>({z:from+300+i*190+(i%3)*30,lane:L[(i*7+1)%3],kind,hit:false}));

export default function EndlessRun(){
 const router=useRouter();
 const canvas=useRef<HTMLCanvasElement>(null); const ball=useRef({z:0,lane:0,target:0,speed:8.5,boost:0,slow:0,spring:0}); const track=useRef<Ob[]>(makeTrack(0));
 const started=useRef(false),paused=useRef(false),score=useRef(0),distance=useRef(0); const [playing,setPlaying]=useState(false),[pause,setPause]=useState(false),[over,setOver]=useState(false),[coins,setCoins]=useState(0),[best,setBest]=useState(0),[count,setCount]=useState<number|null>(null);
 const again=()=>{ball.current={z:0,lane:0,target:0,speed:8.5,boost:0,slow:0,spring:0};track.current=makeTrack(0);score.current=0;distance.current=0;setCoins(0);setOver(false);setPause(false);paused.current=false;started.current=false;setCount(3);let n=3;const t=setInterval(()=>{n--;if(n<=0){clearInterval(t);started.current=true;setPlaying(true)}else setCount(n)},650)};
 useEffect(()=>{again();return()=>{started.current=false}},[]);
 useEffect(()=>{const x=canvas.current;if(!x)return;const q=x.getContext('2d');if(!q)return;let raf=0,last=performance.now(),w=0,h=0,tx=0;const keys=new Set<string>();
 const resize=()=>{const b=x.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);w=b.width;h=b.height;x.width=w*d;x.height=h*d;q.setTransform(d,0,0,d,0,0)};
 const kd=(e:KeyboardEvent)=>{keys.add(e.key.toLowerCase());if(['arrowleft','arrowright','a','d',' '].includes(e.key.toLowerCase()))e.preventDefault()}; const ku=(e:KeyboardEvent)=>keys.delete(e.key.toLowerCase());
 const ts=(e:TouchEvent)=>{tx=e.touches[0]?.clientX||0}; const tm=(e:TouchEvent)=>{if(!started.current||paused.current)return;const nx=e.touches[0]?.clientX||tx,dx=nx-tx;if(Math.abs(dx)>18){ball.current.target=Math.max(-1,Math.min(1,ball.current.target+(dx>0?1:-1)));tx=nx}e.preventDefault()};
 const item=(o:Ob,xx:number,yy:number,s:number)=>{q.save();q.translate(xx,yy);q.scale(s,s);q.textAlign='center';q.font='900 9px system-ui';if(o.kind==='coin'){q.fillStyle='#facc15';q.beginPath();q.arc(0,0,11,0,Math.PI*2);q.fill();q.fillStyle='#713f12';q.fillText('$',0,4)}if(o.kind==='boost'){q.fillStyle='#22d3ee';q.fillRect(-28,-7,56,14);q.fillStyle='#032b35';q.fillText('BOOST',0,4)}if(o.kind==='spring'){q.strokeStyle='#c084fc';q.lineWidth=4;q.beginPath();q.moveTo(-14,8);for(let i=0;i<5;i++)q.lineTo(-14+i*7,i%2?-8:8);q.stroke()}if(o.kind==='slow'){q.fillStyle='#2563eb';q.fillRect(-28,-7,56,14);q.fillStyle='#fff';q.fillText('SLOW',0,4)}if(o.kind==='kill'){q.fillStyle='#ef4444';q.beginPath();q.moveTo(0,-16);q.lineTo(15,12);q.lineTo(-15,12);q.closePath();q.fill();q.fillStyle='#fff';q.fillText('!',0,7)}q.restore()};
 const loop=(now:number)=>{const dt=Math.min(.033,(now-last)/1000);last=now;const m=ball.current;
  if(started.current&&!paused.current){const dir=(keys.has('arrowleft')||keys.has('a')?-1:0)+(keys.has('arrowright')||keys.has('d')?1:0);if(dir)m.target=Math.max(-1,Math.min(1,m.target+dir*dt*3.5));const wanted=m.slow>0?4.5:m.boost>0||keys.has(' ')?13:8.5;m.speed+=(wanted-m.speed)*Math.min(1,dt*5);m.lane+=(m.target-m.lane)*Math.min(1,dt*10);if(m.boost>0)m.boost=Math.max(0,m.boost-dt);if(m.slow>0)m.slow=Math.max(0,m.slow-dt);if(m.spring>0){m.spring=Math.max(0,m.spring-dt);m.speed+=12*dt}m.z+=m.speed*dt*60;distance.current=m.z;
   for(const o of track.current){if(o.hit)continue;const dz=o.z-m.z;if(dz>=-10&&dz<=28&&Math.abs(o.lane-m.lane)<=.42){o.hit=true;if(o.kind==='coin'){score.current+=25;setCoins(score.current)}if(o.kind==='boost'){m.boost=2.2;score.current+=10}if(o.kind==='spring'){m.spring=1;score.current+=10}if(o.kind==='slow'){m.slow=2;m.speed*=.5}if(o.kind==='kill'){started.current=false;setPlaying(false);setOver(true)}}}
   const last=track.current[track.current.length-1];if(last&&m.z>last.z-900)track.current=[...track.current,...makeTrack(last.z+150)];
  }
  q.clearRect(0,0,w,h);const g=q.createLinearGradient(0,0,0,h);g.addColorStop(0,'#061a32');g.addColorStop(.55,'#0b3652');g.addColorStop(1,'#03070d');q.fillStyle=g;q.fillRect(0,0,w,h);const hz=h*.28,top=w*.13,bot=w*1.06;q.fillStyle='#182536';q.beginPath();q.moveTo(w/2-top/2,hz);q.lineTo(w/2+top/2,hz);q.lineTo(w/2+bot/2,h);q.lineTo(w/2-bot/2,h);q.closePath();q.fill();for(let z=-1;z<=1;z++){q.strokeStyle='rgba(255,255,255,.2)';q.setLineDash([18,20]);q.beginPath();q.moveTo(w/2+z*top/6,hz);q.lineTo(w/2+z*bot/6,h);q.stroke();q.setLineDash([])}for(const o of track.current){const dz=o.z-m.z;if(o.hit||dz<8||dz>1100)continue;const p=1-dz/1100,y=hz+p*p*(h-hz),rw=top+p*(bot-top);item(o,w/2+o.lane*rw/6,y,.35+p*1.5)}const bx=w/2+m.lane*bot/6;const by=h*.79;const r=Math.max(23,w*.042);const gr=q.createRadialGradient(bx-r*.35,by-r*.4,2,bx,by,r);gr.addColorStop(0,'#fff');gr.addColorStop(.2,'#38bdf8');gr.addColorStop(1,'#06111f');q.fillStyle=gr;q.shadowBlur=18;q.shadowColor='#38bdf8';q.beginPath();q.arc(bx,by,r,0,Math.PI*2);q.fill();q.shadowBlur=0;
  q.fillStyle='rgba(0,0,0,.72)';q.fillRect(14,14,Math.min(520,w-28),86);q.fillStyle='#fff';q.font='900 16px system-ui';q.fillText(`ENDLESS RUN · ${Math.floor(distance.current)}m`,28,40);q.fillStyle='#facc15';q.fillText(`COINS ${score.current}`,28,66);q.fillStyle='#22d3ee';q.fillText(`BEST ${Math.max(best,Math.floor(distance.current))}m`,150,66);
  if(count!==null){q.fillStyle='rgba(0,0,0,.55)';q.fillRect(0,0,w,h);q.fillStyle='#fff';q.textAlign='center';q.font='900 90px system-ui';q.fillText(count,w/2,h*.52);q.textAlign='left'}if(pause){q.fillStyle='rgba(0,0,0,.55)';q.fillRect(0,0,w,h);q.fillStyle='#fff';q.textAlign='center';q.font='900 50px system-ui';q.fillText('PAUSED',w/2,h*.48);q.textAlign='left'}if(over){setBest(v=>Math.max(v,Math.floor(distance.current)));q.fillStyle='rgba(0,0,0,.72)';q.fillRect(0,0,w,h);q.fillStyle='#ef4444';q.textAlign='center';q.font='900 48px system-ui';q.fillText('CRASH!',w/2,h*.45);q.fillStyle='#fff';q.font='700 18px system-ui';q.fillText(`${Math.floor(distance.current)}m · ${score.current} coins`,w/2,h*.52);q.fillText('Tap PLAY AGAIN',w/2,h*.58);q.textAlign='left'}raf=requestAnimationFrame(loop)};resize();window.addEventListener('resize',resize);window.addEventListener('keydown',kd);window.addEventListener('keyup',ku);x.addEventListener('touchstart',ts,{passive:false});x.addEventListener('touchmove',tm,{passive:false});raf=requestAnimationFrame(loop);return()=>{cancelAnimationFrame(raf);window.removeEventListener('resize',resize);window.removeEventListener('keydown',kd);window.removeEventListener('keyup',ku);x.removeEventListener('touchstart',ts);x.removeEventListener('touchmove',tm)}},[]);
 const togglePause=()=>{if(!started.current||over)return;paused.current=!paused.current;setPause(paused.current)};
 return <main className="min-h-screen bg-[#02060d] p-3 text-white sm:p-5"><div className="mx-auto max-w-[1500px]"><header className="mb-3 flex items-center justify-between rounded-2xl border border-white/10 bg-white/[.04] p-4"><button onClick={()=>router.push('/jusu-rush')} className="text-xs font-bold text-slate-500">← MODES</button><b className="text-cyan-400">JUSU RUSH</b><b className="text-amber-300">ENDLESS RUN</b></header><div className="overflow-hidden rounded-2xl border border-white/10 bg-black"><canvas ref={canvas} className="block h-[68vh] min-h-[520px] w-full touch-none"/></div><div className="mt-3 flex flex-wrap justify-center gap-2"><button onClick={again} className="rounded-xl bg-white px-5 py-3 text-xs font-black text-black">↻ PLAY AGAIN</button><button onClick={togglePause} disabled={!playing||over} className="rounded-xl bg-white/10 px-5 py-3 text-xs font-black disabled:opacity-30">{pause?'▶ PLAY':'⏸ PAUSE'}</button></div><p className="mt-2 text-center text-xs text-slate-500">Touch-drag left/right · A/D or ←/→ · Collect coins · Survive as long as possible</p></div></main>
}