'use client';
import Link from 'next/link';
import ProductNav from '@/components/product-nav';
import { useSavings } from '@/hooks/use-savings';
import { rewardLevel, pointsToNextLevel } from '@/lib/rewards';
import { Trophy, Gamepad2, PiggyBank, Zap, ArrowRight } from 'lucide-react';

export default function Rewards(){
 const { savings } = useSavings();
 const points = savings.length * 10;
 const level = rewardLevel(points);
 return <><ProductNav/><main className="mx-auto max-w-7xl p-4 py-8 sm:p-8"><div className="mb-8"><p className="text-sm font-bold text-primary">JUSU REWARDS</p><h1 className="text-3xl font-black tracking-tight">Save. Race. Earn.</h1><p className="mt-2 text-muted-foreground">Your savings activity and JUSU RUSH achievements build one reward balance.</p></div><section className="mb-6 rounded-[28px] border border-primary/15 bg-gradient-to-br from-primary/[.12] via-card to-card p-6 sm:p-8"><div className="flex flex-col gap-6 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-semibold text-muted-foreground">Current reward points</p><p className="mt-2 text-5xl font-black">{points}</p><p className="mt-2 text-sm text-muted-foreground">Level {level} · {pointsToNextLevel(points)} points to next level</p></div><div className="flex h-20 w-20 items-center justify-center rounded-3xl bg-primary/10"><Trophy className="h-10 w-10 text-primary"/></div></div><div className="mt-6 h-3 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{width:`${Math.min(100, points%100)}%`}}/></div></section><div className="grid gap-5 md:grid-cols-3"><div className="rounded-3xl border bg-card p-6"><PiggyBank className="h-6 w-6 text-primary"/><h2 className="mt-5 font-black">Save</h2><p className="mt-2 text-sm text-muted-foreground">Every recorded contribution earns points.</p><p className="mt-5 text-2xl font-black">+10</p><p className="text-xs text-muted-foreground">per contribution</p></div><div className="rounded-3xl border bg-card p-6"><Gamepad2 className="h-6 w-6 text-cyan-400"/><h2 className="mt-5 font-black">RUSH</h2><p className="mt-2 text-sm text-muted-foreground">Race, collect coins and finish courses to earn rewards.</p><p className="mt-5 text-2xl font-black">+5</p><p className="text-xs text-muted-foreground">race entry</p></div><div className="rounded-3xl border bg-card p-6"><Zap className="h-6 w-6 text-yellow-400"/><h2 className="mt-5 font-black">Milestones</h2><p className="mt-2 text-sm text-muted-foreground">Finishing a race gives a bigger achievement bonus.</p><p className="mt-5 text-2xl font-black">+25</p><p className="text-xs text-muted-foreground">race finish</p></div></div><Link href="/jusu-rush" className="mt-6 flex items-center justify-between rounded-3xl border border-cyan-400/20 bg-cyan-500/[.06] p-6 hover:border-cyan-400/50"><span><b className="block font-black">Ready to earn more?</b><small className="text-muted-foreground">Jump into JUSU RUSH.</small></span><ArrowRight className="h-5 w-5 text-cyan-400"/></Link></main></>
}
